### ISSUE TITLE
 Moving objects by dragging rather than 'teleporting' them

### ISSUE THREAD

**Issue by robertjuh** [google-ar/three.ar.js#101]
Hello,

Would it be possible to move objects over a plane with a drag motion? This instead of the process of tapping on a place in the plane and the object will teleport or clone there?

If it's not made yet, i could give it a try to make it myself but i'm not sure where to start maybe you have suggestions?

**Comment by jsantell** [comment]
There's a demo of a more interactable placement/rotation/moving explained in [this blog post](https://www.blog.google/products/google-vr/augmented-reality-web-everyone/), and the [code](https://github.com/google-ar/WebAR-Article) and [live demo](https://google-ar.github.io/WebAR-Article/public/) are available as well that should be a good start!
