### ISSUE TITLE
three.ar.js vs ar.js?

### ISSUE THREAD

**Issue by yuen33** [google-ar/three.ar.js#105]
Does anybody know what is the difference between three.ar.js vs ar.js?

**Comment by jsantell** [comment]
AR.js uses getUserMedia to find a marker and updates per frame the relevant transform of the marker in 0,0,0 space. three.ar.js is a helper library wrapping [experimental AR browser APIs](https://developers.google.com/ar/develop/web/getting-started), using ARKit/ARCore under the hood for scene understanding, anchoring and pose reconstruction. The experimental APIs used here are slowly being standardized into the WebXR spec, and the first proposals should be landing very soon at https://github.com/immersive-web/proposals
