### ISSUE TITLE
QUESTION: Extended tracking w or w/o SLAM

### ISSUE THREAD

**Issue by jgwinner** [google-ar/three.ar.js#106]
##### Description:

Hello! Fantastic library. I have a question:

Is it possible to do 'extended tracking' meaning:

1) Scan a marker
2) Display some content 'behind' the user or around them.
3) User turns to look at the Augmented content, tracking continues.

I'm looking for something similar to this:

[https://samples.argonjs.io/directionswebgl/](https://samples.argonjs.io/directionswebgl/) 

with the wrinkle that in my code, instead of "North" etc. there would be arrows; the arrows would direct users to other locations based on the marker that had been scanned. 

Thank you,

== John ==

**Comment by jsantell** [comment]
You get full 6DOF tracking, and there is support for getting the position of a marker, such that you'll always have the pose of the camera, and the marker, and then it's just a matter of positioning something behind the camera pose

**Comment by jgwinner** [comment]
Sure, but if when the marker is out of view, typically the augmented objects disappear. 

In other words, when the AR camera looses track of the makers, any objects attached disappear without "Extended tracking". 

Is that a feature?

**Comment by jsantell** [comment]
You get 6DOF tracking without markers via SLAM in ARCore/ARKit, so the above scenario is still possible even with no markers

**Comment by jgwinner** [comment]
Perfect, thank you!

Odd, Vuforia and Wikitude don't work that way at all, so this is great to know.

== John ==

**Comment by jsantell** [comment]
An advantage of marker localization is it works anywhere getUserMedia exists, but has downsides like you mentioned. An advantage of AR specific browsers is leveraging ARCore/ARKit, but unfortunately needs a separate browser. You can follow along the status of standardizing the AR features to land in production browsers over at https://github.com/immersive-web. Hope this helps!
