### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "transform-class-properties"

### ISSUE THREAD

**Issue by pulkitjuneja** [google-ar/three.ar.js#111]
I am getting this error when trying to install the library via webpack/npm.

**Comment by jsantell** [comment]
The real fix here is removing the non-standard Babel transform-class-properties -- it looks like your build setup is trying to transpile your node_modules. You could change your build to only allow Babel transformations in non-node_modules, or remove the .babelrc in `node_modules/three.ar.js`

**Comment by pulkitjuneja** [comment]
that worked 👍
