### ISSUE TITLE
Any way to get ARPlaneAnchor data ?

### ISSUE THREAD

**Issue by pulkitjuneja** [google-ar/three.ar.js#112]
Is there any way to get the ARplaneAnchor data. I need this so I can compute a PlaneGeometry out of it which i can then use in my physics calculations

**Comment by jsantell** [comment]
You can use the underlying platform APIs that WebARonARKit and WebARonARCore use that three.ar.js wraps around; see the anchor and planes APIs [here](https://github.com/google-ar/three.ar.js/blob/master/webvr_ar_extension.md#anchors). You can also see how the [ARAnchorManager](https://github.com/google-ar/three.ar.js/blob/master/src/ARAnchorManager.js) and [ARPlanes](https://github.com/google-ar/three.ar.js/blob/master/src/ARPlanes.js) are implemented, or see if you could use those directly -- hope this helps!
