### ISSUE TITLE
Update to work with chrome://flags #webxr ?

### ISSUE THREAD

**Issue by jeromeetienne** [google-ar/three.ar.js#113]
Will this repo be updated to work with chrome://flags #webxr ?

**Comment by jsantell** [comment]
Hey @jeromeetienne! Not at this time -- many of the utilities are for WebVR 1.1 which doesn't cleanly translate to WebXR, and the only feature landed for WebXR+AR is a hit test. Once there are more primitives and features landed (or planned) for WebXR+AR, we'll revisit this and see if there's a helpful abstraction to land as three.ar.js. Hope this helps!
