### ISSUE TITLE
See examples in ARCore

### ISSUE THREAD

**Issue by sepehrabdous** [google-ar/three.ar.js#115]
Hello
I have a problem with opening an example on ARCore.
Suppose we have an example that works like those in the examples directory.
How can we make the ARCore to show them because when I clicked on one of the examples on ARCore it just showed me the html code for it.

Thanks.

**Comment by jsantell** [comment]
Information about using these prototype AR browsers [can be found here](https://developers.google.com/ar/develop/web/quickstart). That being said, we're moving towards an implementation in proper Chrome, which you can learn more about [on the Chrome dev blog](https://developers.google.com/web/updates/2018/06/ar-for-the-web)

**Comment by sepehrabdous** [comment]
Thank you very much
Also another solution is opening the html file with github htmlpreview:

[https://stackoverflow.com/questions/8446218/how-to-see-an-html-page-on-github-as-a-normal-rendered-html-page-to-see-preview](https://stackoverflow.com/questions/8446218/how-to-see-an-html-page-on-github-as-a-normal-rendered-html-page-to-see-preview)

Thanks
