### ISSUE TITLE
Location Based AR Example?

### ISSUE THREAD

**Issue by osper66** [google-ar/three.ar.js#122]
##### Description:

Please describe your issue or feature request in detail.
Code and screenshots will help us diagnose the issue.

##### Additional Information:

* three.ar.js version:
* three.js version:
* Browser: iOS 12.x Safari

- [x] WebARonARKit (iOS)
- [ ] WebARonARCore (Android)
- [ ] WebARonTango (Android)
- [x] All

**Comment by osper66** [comment]
Although there are many example of location based AR of ARkit, how about this three.ar.js?

**Comment by jsantell** [comment]
three.ar.js and its browsers do not support location-based AR
