### ISSUE TITLE
Run Dev fails to parse .vert .frag files

### ISSUE THREAD

**Issue by Thirdfloordraft** [google-ar/three.ar.js#22]
This error occurs when attempting to setup a development server. Is there an issue in the loader dependencies?
> ERROR in ./src/shaders/arview.vert
> Module parse failed: C:\Users\Admin\arbuild00\node_modules\three.ar.js\src\shaders\arview.vert Unexpected token (14:10)
> You may need an appropriate loader to handle this file type.
> | // limitations under the License.
> |
> | attribute vec3 aVertexPosition;
> | attribute vec2 aTextureCoord;
> |
>  @ ./src/ARView.js 17:0-49
>  @ ./src/index.js
>  @ multi (webpack)-dev-server/client?http://0.0.0.0:8000 ./src/index.js
> 
> ERROR in ./src/shaders/arview.frag
> Module parse failed: C:\Users\Admin\arbuild00\node_modules\three.ar.js\src\shaders\arview.frag Unexpected character '#' (14:0)
> You may need an appropriate loader to handle this file type.
> | // limitations under the License.
> |
> | #extension GL_OES_EGL_image_external : require
> |
> | precision mediump float;
>  @ ./src/ARView.js 18:0-51
>  @ ./src/index.js
>  @ multi (webpack)-dev-server/client?http://0.0.0.0:8000 ./src/index.js
> 
> ERROR in three.ar.min.js from UglifyJs
> Unexpected character '`' [three.ar.min.js:2299,28]

**Comment by jsantell** [comment]
It looks like you're using three.ar.js as a dependency, which when included will reference the `dist/three.ar.js` file which is already compiled. If you're importing files directly via es6 modules (like `import ARView from 'three.ar.js/src/ARView'`), then you are accessing the uncompiled content and need to support any transformations applied here, like for shaders.

If you're not using it as a dependency, but executing `npm run dev` in three.ar.js, this should work -- did you `npm install`? What version of node/npm?

**Comment by Thirdfloordraft** [comment]
not intending to run it as a dependency, but develop some prototype concept. 

follow the testing instruction, installed via `npm install three three.ar.js`

I did run `npm install` in `three.ar.js` 
currently using `node-v6.11.3-x64`, or should I be upgrading to the latest?

also, thanks for the prompt reply

**Comment by jsantell** [comment]
I think you will have better luck with cloning the repo (`git clone git@github.com:google-ar/three.ar.js.git`) and then going through the steps.

`npm install three three.ar.js` is for installing as a dependency in another project -- if you're just prototyping and not working on the library itself, you can also just include the built file in the source [here](https://github.com/google-ar/three.ar.js/raw/master/dist/three.ar.js)

**Comment by Thirdfloordraft** [comment]
Ah thanks @jsantell 

Sorry about that. Changing gears back into web development, getting sea-legs back

**Comment by jsantell** [comment]
Great, glad it worked out!
