### ISSUE TITLE
possible to enable fullscreen and build the app(warping the html in) ?

### ISSUE THREAD

**Issue by joseeph** [google-ar/three.ar.js#24]
Just try out all the examples, looks really cool, I would going on porting my three.js contents into it and try to build an IOS app.

**Comment by jsantell** [comment]
I'm not sure what you mean by "warping the HTML in" -- can you explain, or have an example?

Also, are you trying to go fullscreen via `requestFullscreen`? (I'm not sure if that works in either of the browsers currently)

**Comment by joseeph** [comment]
@jsantell Thank you for respond. Let me explain in detail.
what I want is basically like:
Enabling fully client side and fullscreen capability with [WebARonARKit](https://github.com/google-ar/WebARonARKit). 

I do try `document.documentElement.webkitRequestFullscreen()` on[WebARonARKit](https://github.com/google-ar/WebARonARKit) app, seems didn't work tho.

**Comment by jsantell** [comment]
This is an issue with [WebARonARKit](https://github.com/google-ar/WebARonARKit) -- I've filed an issue in that repo https://github.com/google-ar/WebARonARKit/issues/27

Thanks for reporting!
