### ISSUE TITLE
Marker example wanted

### ISSUE THREAD

**Issue by LantosIstvan** [google-ar/three.ar.js#42]
Is there any planned example to use with a marker? So always project on the matching graphic, like single or multi markers.

AR.js can do this, but for the marker projection it's using jsartoolkit5, which has a z-fighting issue with some models for years.

Is it possible marker projection without third-party libraries like jsartoolkit5 or aruco?

**Comment by jsantell** [comment]
We have plans on adding this to WebARonARCore and WebARonARKit in the future, but no current ETAs

**Comment by Utopiah** [comment]
Regarding this and https://github.com/google-ar/three.ar.js/issues/61 does it mean Hiro marker, NFT, QRCode or something else? (cf also [marker.html example](https://github.com/google-ar/three.ar.js/blob/master/examples/tango/marker.html) )

**Comment by Utopiah** [comment]
Tried to run https://github.com/google-ar/three.ar.js/blob/master/examples/tango/marker.html on a Pixel2 but failed, checked the console, no error. The passthrough camera only gave the first frame then stopped. Any suggestion?

**Comment by lincolnfrog** [comment]
@Utopiah the tango examples only work on tango devices

**Comment by judax** [comment]
We are working on pushing a correct marker example that should work on both WebARonARCore and WebARonTango.

**Comment by jsantell** [comment]
Fixed in #83
