### ISSUE TITLE
Documentation is not adequate

### ISSUE THREAD

**Issue by jagtapAmit** [google-ar/three.ar.js#43]
Need good documentation or readme explaining the details of api and usage . A simple example explaining the basic  html and js code setup will be very helpful.
Api method definitions and summary will be good or links pointing to docs.

**Comment by jsantell** [comment]
There are a [handful of one-page examples](https://github.com/google-ar/three.ar.js/tree/master/examples) in this source, and documentation on the [API](https://github.com/google-ar/three.ar.js/blob/master/API.md) can also be found. Hope this helps!
