### ISSUE TITLE
Keep webpack

### ISSUE THREAD

**Issue by lunzhang** [google-ar/three.ar.js#62]
Is it possible to keep webpack for development purposes and use rollup just for production build.

**Comment by jsantell** [comment]
Two different pipelines would be harder to maintain and ensure we're getting the same content in both dev and production -- may I ask why the Webpack preference? The only dev facing change is the lack of `webpack-dev-server`, but something similar can be implemented with something like [rollup-plugin-serve](https://github.com/thgh/rollup-plugin-serve)

**Comment by lunzhang** [comment]
I wanted to keep `webpack-dev-server ` for serving so it's easier to access from my phone.  Didn't know about the plugin.

**Comment by jsantell** [comment]
The rollup patch has been bitrotting for a bit so just wanted to get it in, but I can look into adding rollup-plugin-serve as well. In the mean time, running `npm run watch` with something like `simplehttpserver` to serve content will get the same functionality as before
