### ISSUE TITLE
light estimation from AR sdks

### ISSUE THREAD

**Issue by jimmy-jam** [google-ar/three.ar.js#64]
Both ARKit and ARCore estimate the lighting in the scene as part of their features.  I would like to use this lighting estimation in webAR.  This may imply separate issues on webARonARKit and webARonARCore to pass those values up to javascript from native code.  Also, this feature could be implemented slightly differently on the two platforms of interest, so a "typeofestimation" flag might have to be passed up as well.  

https://developer.apple.com/documentation/arkit/arlightestimate
https://developers.google.com/ar/reference/java/com/google/ar/core/LightEstimate

**Comment by jsantell** [comment]
Thanks for reporting! Light estimation is currently on our roadmap for both browsers.
