### ISSUE TITLE
point cloud from AR sdks

### ISSUE THREAD

**Issue by jimmy-jam** [google-ar/three.ar.js#65]
Both ARKit and ARCore provide a sparse point cloud: I want to use this from my JS web app.  Provide a way to send these values up, as well as choosing to enable/disable this feature dynamically, since it could get expensive to use all the time.  

There seems to be some experimental code for something along these lines already:
https://github.com/google-ar/three.ar.js/tree/master/src/experimental

https://developers.google.com/ar/reference/java/com/google/ar/core/PointCloud
https://developer.apple.com/documentation/arkit/arpointcloud

**Comment by jsantell** [comment]
The experimental point cloud code is for [WebARonTango](https://github.com/google-ar/WebARonTango) which features depth point clouds, which isn't possible on ARCore/ARKit (which has feature point clouds). Now that ARCore also has feature points, this might be something we can explore. Thanks for filing!

**Comment by stewdio** [comment]
First: Thank you!! This repo and its corresponding WebARonARCore and WebARonARKit are awesome. Really fun to play with :smile:

I’ve noticed that the `tango/occlusion.html` code is missing [`TeapotBufferGeometry.js`](https://threejs.org/examples/js/geometries/TeapotBufferGeometry.js) from this repo—though the `script` tag indicates it ought to be in `third_party/three.js/`. Thankfully that file was easy to find online.

But more perplexing is that the `VRPointCloudWrapper` class internally calls a `VRPointCloud` class that I just can’t seem to find anywhere. I took a quick peek for it in the [WebARonTango](https://github.com/google-ar/WebARonTango) repo but didn’t see it there either. Can haz `VRPointCloud`?

**Comment by jsantell** [comment]
@stewdio Thanks for catching the missing TapotBufferGeometry in that example! These prototypes were initially on WebARonTango before we released WebARonARCore and WebARonARKit, which don't have depth points so anything in the `tango` directory won't work there. WebARonTango provides a global [window.VRPointCloud](https://github.com/google-ar/WebARonTango/blob/master/chromium/src/third_party/WebKit/Source/modules/vr/VRPointCloud.idl) available via `vrDisplay.getPointCloud` which is used in that example

**Comment by eric-schleicher** [comment]
So this makes it sounds like if we sling depth maps over to the device, we can polyfill or provide a pointcloud emitter using the ArCore pose (+ an known offset).   off to 3d-print a bracket.

**Comment by jsantell** [comment]
@eric-schleicher I'm not sure I follow -- ARCore-based experimental AR browsers do not have any way of currently exposing their *feature points* and do not have *depth points*, however Tango-based AR browsers have the ability to get *depth point* data on the web

**Comment by eric-schleicher** [comment]
I was referring to providing a depth map from an external device (over websockets), and using the ArCore pose to reconstitute/emit clouds. (IIRC there is a three.js example of this; with a static pose [here](https://threejs.org/examples/webgl_kinect.html).  The example is pretty trick, pushing data via compressed webm video.  


Polyfilling this onto the Window Object provides for an (immediate) substitute, This way we don't have to wait for son-of-tango hardware.  (some would say "free" from tango)

My comment was more along the lines that building a solution that works similarly to the tango example(s) would line it up when depth sensor output make a return to the ~~tango~~ ArCore API.

**Comment by jsantell** [comment]
Should be possible, anything in 3D space using the same coordinate system as ARCore should have that effect

**Comment by stewdio** [comment]
@jsantell Thanks for the quick response!

I see what you mean about `VRPointCloud` originally being for depth point clouds in WebARon**Tango**, but I was hoping the same mechanism would, for WebARon**ARCore**, yield feature point clouds. (Because on the JavaScript side we’re still just asking the `vrDisplay` instance to hand over a bunch of [PointCloud](https://developers.google.com/ar/reference/java/com/google/ar/core/PointCloud) XYZ and confidence values, right? Same data format as Tango’s depth point clouds?)

But this is where I also have to step back and admit I am very new to this and it’s pretty likely I haven’t fully wrapped my head around what you’re trying to tell me :wink:

**Comment by eric-schleicher** [comment]
@stewdio, you're talking about something along the line of this?

https://www.youtube.com/watch?time_continue=1&v=-yhAl7i-D0c

Using the sparse clouds.

**Comment by Utopiah** [comment]
Skeptical, without a depth camera will provide a pointcloud so sparse I doubt it would be practically unusable. Makes me wonder what kind of use case would benefit from it rather than the current horizontal (and hopefully vertical too soon) planes.

**Comment by jsantell** [comment]
> I see what you mean about VRPointCloud originally being for depth point clouds in WebARonTango, but I was hoping the same mechanism would, for WebARonARCore, yield feature point clouds. (Because on the JavaScript side we’re still just asking the vrDisplay instance to hand over a bunch of PointCloud XYZ and confidence values, right? Same data format as Tango’s depth point clouds?)

In the end, the format for point clouds are the same between feature points and depth points, while semantically different. ARCore/ARKit based browsers do not currently expose their feature points to the web (the origin of this issue being opened)

**Comment by jsantell** [comment]
AR proposals are now landing in the Immersive Web organization: [hit-test](https://github.com/immersive-web/hit-test), [anchors](https://github.com/immersive-web/anchors) -- closing this, as this will be addressed by the WebXR standard
