### ISSUE TITLE
Create a gist to an .md file for community based WebAR demos

### ISSUE THREAD

**Issue by judax** [google-ar/three.ar.js#7]
Create a gist so developers can comment and provide links to the experiments they build using the prototype browsers and three.ar.js. We will need proper documentation both in the repos and in the devsite to explain how the gist works and how to add new links. The devsite should have a link to the experiments .md file.

**Comment by jsantell** [comment]
Created a gist:
https://gist.github.com/jsantell/871d7e709e5007533f3bf07c35434e29
