### ISSUE TITLE
Bring this to the web

### ISSUE THREAD

**Issue by nexflo** [google-ar/three.ar.js#82]
Besides using native components it would be cool bringing this to the native web as well. Yes i know - no easy task. :)

**Comment by jsantell** [comment]
We've begun work with other browser vendors on standardizing the AR API -- will follow up and close when the appropriate WG link is available (in the next few days/weeks?)

**Comment by nexflo** [comment]
Awesome!

**Comment by nitin42** [comment]
Awesome! I can anticipate that this will impact the development workflow overall when building the stuff with `three.ar.js`. I'm working on integrating this project with `React`. Why ?

* Reduces the learning curve
* React community will learn about this project
* Impacts the visibility

Apart from this, one thing that hinders my work is that, right now I cannot locally create a project using `three.ar.js` like making some changes and then reloading similar to web dev env.

Any idea/suggestions how this space can be expand?

**Comment by nitin42** [comment]
Between I'm working on this - https://github.com/nitin42/React-Web-AR

**Comment by jsantell** [comment]
@nitin42 you can use live reloading like you would for local desktop dev by using chrome remote debugging [mentioned here](https://github.com/google-ar/WebARonARCore#5-debugging) -- still need a phone/cable set up, but makes it a bit nicer

**Comment by nitin42** [comment]
👍

**Comment by PerspectivesLab** [comment]
any updates on the integration and standards ?

**Comment by jsantell** [comment]
From the W3C call on February 27th, the initial AR proposals should be landing in the [immersive-web/proposals](https://github.com/immersive-web/proposals/) organization sometime in the next week, and move to their own repos following community approval.

Closing this issue for now as it's being handled in the WG
