### ISSUE TITLE
The explanation about `updateProjectionMatrix()`

### ISSUE THREAD

**Issue by ega1979** [google-ar/three.ar.js#85]
The explanation about `getProjectionMatrix` exists at API.md.
However, `getProjectionMatrix` itself is not used in all example and only `updateProjectionMatrix` is used in examples.
But `updateProjectionMatrix` is not explained about at API.md. I understand `getProjectionMatrix()` is used in `updateProjectionMatrix()`.
So, what does it mean `updateProjectionMatrix()`?

And, where should I refer to 'projectionMatrix' property at three.ar.js. It seems not to be exist.

* three.ar.js version: 1.6

**Comment by lincolnfrog** [comment]
getProjectionMatrix is a way for you to get the projection matrix if you want to use that information in your app. We don't currently have an example that needs to do math based on the projection matrix. updateProjectionMatrix() is what you call if the projection matrix needs to be recalculated - you can see in the examples it gets called when the near/far planes or device orientation changes. Most of the time the projection matrix is set at the beginning and doesn't need to be updated after that (unless the device orientation changes).

camera.projectionMatrix does indeed exist.

**Comment by jsantell** [comment]
The ARPerspectiveCamera inherits from three's [PerspectiveCamera](https://threejs.org/docs/#api/cameras/PerspectiveCamera) -- using updateProjectionMatrix on ARPerspectiveCamera is used in the same way; and like @lincolnfrog said, shouldn't be necessary most likely
