### ISSUE TITLE
Creating custom planes

### ISSUE THREAD

**Issue by cosmo-naut** [google-ar/three.ar.js#94]
How much support does ARCore and by extension three.ar,js have for managing custom planes? For example, can I extend the length or manually size a plane detected?

I understand that having the webAR wrapper does limit the access available to a developer, however I was wondering if there are any pathways to directly manage a plane.

Furthermore, this may be more of an ARCore question, but I understand that plane detection only currently supports convex 2d planes, is this correct? Thank you

**Comment by jsantell** [comment]
> How much support does ARCore and by extension three.ar,js have for managing custom planes? For example, can I extend the length or manually size a plane detected? I understand that having the webAR wrapper does limit the access available to a developer, however I was wondering if there are any pathways to directly manage a plane.

The planes exposed are directly from the scene understanding capabilities of ARCore/ARKit -- you can extend these in your own code and do whatever you'd like with them (double the size of all planes, make all planes very large or "infinite", make assumptions about areas between planes if they're on the same Z plane, etc.), but the API focused on providing as much information as possible from the platform's scene understanding and to be building blocks or primitives for any experience, so the API will not support altering these planes in anyway. However you can use these building blocks to manipulate planes however you'd like.

> Furthermore, this may be more of an ARCore question, but I understand that plane detection only currently supports convex 2d planes, is this correct? Thank you

[Correct, ARCore supports 2D convex planes, and ARKit supports 2D rectangular planes.](https://github.com/google-ar/three.ar.js/blob/master/webvr_ar_extension.md#getting-planes-data)

Hope this helps! :smile:

**Comment by cosmo-naut** [comment]
Is there a specific object that manages these planes that I should investigate extending? I'm not entirely sure where I'd begin

I've answered my own question. For the curious:
src/ARPlanes.js handles the plane related events given to us by ARCore.
three.ar.js also has an ARPlanes class that is a duplicate of ARPlanes.js, I imagine it would do the same job.
I am unclear whether I need to instantiate an ARPlanes object in my code to access it, or if there is an object already doing that behind the scenes

**Comment by jsantell** [comment]
`src/ARPlanes.js` is used by the ARDebug utility for visualizing planes, although not exposed as it's rather opinionated and everyone will want to use planes differently. [The docs show how to listen to planes via the VRDisplay](https://github.com/google-ar/three.ar.js/blob/master/webvr_ar_extension.md#getting-planes-data) and from there can be manipulated. The [surfaces](https://github.com/google-ar/three.ar.js/blob/master/examples/surfaces.html) demo uses the ARDebug plane visualization if you'd like to see where planes are, but I imagine it would be difficult editing and manipulating these in a way that's different from the true scene understanding.
