### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by erikparr** [google-ar/three.ar.js#97]
##### Description:

Hi - Very nice project here. I'm exploring your examples and I keep getting the following error on plane finder example.  I am on WebARonARKit, ios 11.2.5 three.js .89, and three.ar.js 1.7
![img_0038](https://user-images.githubusercontent.com/896122/35981969-e0bd6c7e-0cee-11e8-9d91-df47fd2dc7e5.PNG)
Thanks

**Comment by jsantell** [comment]
Thanks for filing this issue! This looks like a [WebARonARKit](https://github.com/google-ar/WebARonARKit) issue however, could you refile there?

Thank you!
